### ISSUE TITLE
Show ready maps button

### ISSUE THREAD

**Issue by leins275** [LanskovNV/MapViewer#6]
Maybe it'll be better to remove that button and always present thel list of maps?

**Comment by sevarsh** [comment]
I think so

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leins275** [comment]
So it seems to me that we have for you a new task)

**Comment by sevarsh** [comment]
And maybe « show ready maps » label has to be just a bold text string. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leins275** [comment]
Yes, but "Prepared maps"

**Comment by leins275** [comment]
It's better

**Comment by sevarsh** [comment]
>Yes, but "Prepared maps"

@LanskovNV yes, it looks better

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sevarsh** [comment]
>So it seems to me that we have for you a new task)

@LanskovNV i see

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tumanov-Viatcheslav** [comment]
You just  need to find how to start action on loading page

**Comment by leins275** [comment]
Let's discuss it later, some architecture changes needed

**Comment by sevarsh** [comment]
Ok, it's up to discuss
