### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by leins275** [LanskovNV/MapViewer#7]
Another redesign idea - Header is too big, maybe it's a good idea to give it max heigth, and also integrate navigation buttons to banner... Please, think about it.

**Comment by leins275** [comment]
@Tumanov-Viatcheslav , Maybe you can manage this?

**Comment by Tumanov-Viatcheslav** [comment]
I think we should leave buttons, it should be more user-friendly. If they are to big how about changing font from 16 to maybe 14

**Comment by leins275** [comment]
Ok, let's discuss this on call

**Comment by sevarsh** [comment]
Ok
